Deploy to Optimism
pooltogether/v4-mainnet pull request #14
Opened 2022-06-17 22:35 UTC by McOso

### v1.6.0 introduces Optimism deployment

# WARNING: Do Not Merge
This initial PR allows for code review before actually deploying.

### TODO:
 - Deploy to Optimism Mainnet
 - Verify Contracts
 - Generate new contracts.json
 - Generate new docs and PR to docs repo

2022-06-20 16:07 UTC, PierrickGT commented
@McOso you will also need to publish a new version of v4-mainnet package on NPM but you may not be able to if you are not part of the PoolTogether Inc team on NPM. If you can't, I'll take care of it.

2022-06-20 20:42 UTC, PierrickGT requested changes
A few changes are needed. 
It would be good to run `yarn format:file deploy/v1.6.0/optimism.ts` to lint the deploy script and enjoy a better code formatting.

2022-06-20 20:42 UTC, PierrickGT commented on deploy/v1.6.0/optimism.ts
> +  })
Add the `skipIfAlreadyDeployed: true` option for all `deployAndLog`.

2022-06-20 23:29 UTC, kamescg commented on deploy/v1.6.0/optimism.ts
> +  const prizeTierHistoryResult = await deployAndLog('PrizeTierHistory', { from: deployer, args: [deployer] })
I don't necessarily agree we need to set these values when we deploy. They can be set after the fact, and imho is probably ideal so everyone can review the transaction that sets these critical parameters.

2022-06-20 23:30 UTC, kamescg commented on deploy/v1.6.0/optimism.ts
> +  const prizeDistributorResult = await deployAndLog('PrizeDistributor', { from: deployer, args: [executiveTeam, ticketResult.address, drawCalculatorResult.address] })
Thank goodness we are going to finally fix this bug. Has caused us multiple headaches in the past since it was copied/pasted multiple times.

2022-06-23 20:49 UTC, McOso commented
> @McOso you will also need to publish a new version of v4-mainnet package on NPM but you may not be able to if you are not part of the PoolTogether Inc team on NPM. If you can't, I'll take care of it.

You're right I do not have the proper permissions and will need your help.

2022-06-23 20:51 UTC, McOso commented on deploy/v1.6.0/optimism.ts
> +  const prizeTierHistoryResult = await deployAndLog('PrizeTierHistory', { from: deployer, args: [deployer] })
The DeWork bounty requirements say to leave this up to the Executive Team to set after deployment.

2022-06-23 22:04 UTC, PierrickGT approved these changes

2022-06-30 21:07 UTC, asselstine commented
Some last changes:

- Rebase onto latest.  It appears to be missing the 1.5.1 deployment
- Update `aave-yield-source` and `aave-v3-yield-source` packages to latest versions (1.2.0 and 1.1.0, respectively)

Otherwise, looks good to me!

2022-07-01 02:18 UTC, McOso commented
> Some last changes:
> 
> * Rebase onto latest.  It appears to be missing the 1.5.1 deployment
> * Update `aave-yield-source` and `aave-v3-yield-source` packages to latest versions (1.2.0 and 1.1.0, respectively)
> 
> Otherwise, looks good to me!

Yield source packages have been updated. The code is up-to-date with the latest, unless I am missing something? The v1.5.1 re-deploy didn't create a new 1.5.1 folder in the `Deploy` directory, so I think it is misleading

2022-07-01 15:30 UTC, PierrickGT commented on deploy/v1.6.0/optimism.ts
> +      'PoolTogether aOptUSDC Yield',
The name should come first.
```suggestion
      'PoolTogether aOptUSDC Yield',
      'PTaOptUSDCY',
```

2022-07-01 15:49 UTC, PierrickGT approved these changes

2022-07-01 21:35 UTC, merged