[WIP] Deploy Scripts for DPR Upgrade
pooltogether/v4-mainnet pull request #18
Opened 2022-11-30 22:58 UTC by dylandesrosier

- Adds migrations for each chain to deploy a `PrizeTierHistoryV2` and a `PrizeDistributionFactoryV2`

2022-12-03 00:11 UTC, PierrickGT requested changes

2022-12-03 00:11 UTC, PierrickGT commented on deploy/v1.8.0/avalanche.ts
> +  if (process.env.DEPLOY === 'v1.8.0.avalanche') {
Will be `v1.10.0` since we have to deploy the Optimism bridge update before.

2022-12-03 00:11 UTC, PierrickGT commented on deploy/v1.8.0/avalanche.ts
> +  const pdb = await hre.deployments.get('PrizeDistributionBuffer');
Rename with the full name:
```suggestion
  const prizeDistributionBuffer = await hre.deployments.get('PrizeDistributionBuffer');
```

2022-12-03 00:11 UTC, PierrickGT commented on deploy/v1.8.0/avalanche.ts
> +    `NOTE: The final step to complete the update is a transition of the manager role on the PrizeDistributionBuffer at ${pdb.address} to be the newly deployed PrizeDistributionFactoryV2.`,
And don't forget to update the PrizeDistributor to call the DrawCalculator directly and not the DrawCalculatorTimelock: `prizeDistributor.setDrawCalculator(drawCalculatorAddress)`
⇒ it removes the DrawCalculatorTimelock from the architecture

2022-12-03 00:11 UTC, PierrickGT commented on package.json
> +    "deploy:v1.8.0.avalanche": "DEPLOY=v1.8.0.avalanche hardhat deploy --network avalanche",
```suggestion
    "deploy:v1.10.0.mainnet": "DEPLOY=v1.10.0.mainnet hardhat deploy --network mainnet",
    "deploy:v1.10.0.optimism": "DEPLOY=v1.10.0.optimism hardhat deploy --network optimism",
    "deploy:v1.10.0.polygon": "DEPLOY=v1.10.0.polygon hardhat deploy --network polygon",
    "deploy:v1.10.0.avalanche": "DEPLOY=v1.10.0.avalanche hardhat deploy --network avalanche",
```

2022-12-12 22:14 UTC, PierrickGT requested changes

2022-12-13 15:24 UTC, dylandesrosier commented on deploy/v1.9.0/avalanche.ts
> + * NOTE: The final step to complete the update is a transition of the manager role on a PrizeDistributionBuffer to be the newly deployed PrizeDistributionFactoryV2.
To be in line with my reasoning for the other setup I'm going to add the transitioning of `manager` on the `PrizeDistributionBuffer` with a check and a log.

2023-01-03 10:35 UTC, PierrickGT approved these changes

2023-01-26 20:42 UTC, merged